# Generated by Django 5.2.1 on 2025-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='estimated_price',
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_traveled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
